# Generated by Django 5.0.6 on 2024-06-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalv2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_email',
            field=models.EmailField(default='gvillahermisa@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
