# Generated by Django 5.0.4 on 2024-06-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_student_sanction_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='time_rendered',
        ),
        migrations.AlterField(
            model_name='communityservicetracker',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='communityservicetracker',
            name='time_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='communityservicetracker',
            name='time_out',
            field=models.TimeField(),
        ),
    ]
