# Generated by Django 5.0.4 on 2024-06-07 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_communityservicetracker_time_rendered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmoral',
            name='req_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodmoral',
            name='req_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodmoral',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.student'),
        ),
        migrations.AlterField(
            model_name='goodmoral',
            name='case_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.caseprofile'),
        ),
    ]
