# Generated by Django 5.0.4 on 2024-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_goodmoral_req_date_goodmoral_req_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmoral',
            name='req_status',
        ),
        migrations.AddField(
            model_name='goodmoral',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodmoral',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
