# Generated by Django 5.0.4 on 2024-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_goodmoral_req_status_goodmoral_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmoral',
            name='req_date',
        ),
        migrations.AddField(
            model_name='goodmoral',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sanction',
            field=models.CharField(blank=True, choices=[('apology_letter', 'Apology Letter'), ('community_service', 'Community Service'), ('suspension', 'Suspension'), ('apology_letter_community_service', 'Apology Letter and Community Service'), ('expulsion', 'Expulsion')], max_length=50, null=True),
        ),
    ]
