# Generated by Django 5.0.6 on 2024-06-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_goodmoral_req_date_goodmoral_decision_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Studentinfo',
        ),
    ]
